"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path # importamos pathlib para manejar rutas
import os # importamos os para manejar el sistema operativo
from decouple import config, Csv # importamos config y Csv para manejar las variables de entorno

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent # "che django, tu casa es la carpeta blog"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-CHANGE-ME-IN-PRODUCTION')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool) # para mostrar los errores en el navegador

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',  # panel admin
    'django.contrib.auth',  # autenticación
    'django.contrib.contenttypes',  # tipos de contenido
    'django.contrib.sessions',  # sesiones
    'django.contrib.messages',  # mensajes flash
    'django.contrib.staticfiles', # css/js/img
    'django_ckeditor_5', # editor de texto rich text para las reseñas
    'movies', # app de peliculas, nuestra app principal
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', # seguridad
    'django.contrib.sessions.middleware.SessionMiddleware', # sesiones
    'django.middleware.common.CommonMiddleware', # middleware comun
    'django.middleware.csrf.CsrfViewMiddleware', # anti ataque CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware', # autenticación
    'django.contrib.messages.middleware.MessageMiddleware', # mensajes flash
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # anti ataque clickjacking malicioso
]

ROOT_URLCONF = 'blog.urls' # urls de la app

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', # motor de plantillas
        'DIRS': [BASE_DIR / 'templates'], # django, buscá las templates aca
        'APP_DIRS': True, # django, buscá las templates en las apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application' # wsgi, para que django se comunique con el servidor web


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3', # base de datos sqlite3, archivo unico
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', # No Similar al username
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', # Longitud minima
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', # Contraseña comun
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', # Contraseña numerica
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] # donde estan los archivos estaticos
STATIC_ROOT = BASE_DIR / 'staticfiles' # donde se guardan los archivos estaticos

MEDIA_URL = '/media/' # donde estan los archivos multimedia
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # donde se guardan los archivos multimedia

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de autenticación
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# CKEditor 5 settings
CKEDITOR_5_UPLOAD_PATH = "uploads/"

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', '|',
                    'undo', 'redo'],
        'height': '300px',
        'width': '100%',
        'language': 'es',
    },
    'comment': {
        'toolbar': ['bold', 'italic', '|', 'undo', 'redo'],
        'height': '150px',
        'width': '100%',
        'language': 'es',
        'placeholder': 'Escribe tu comentario... Usa negritas para destacar puntos importantes. 🎬',
    }
}
