# Generated by Django 5.2.3 on 2025-07-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='has_spoilers',
            field=models.BooleanField(default=False, verbose_name='Contiene spoilers'),
        ),
        migrations.AddField(
            model_name='review',
            name='has_spoilers',
            field=models.BooleanField(default=False, verbose_name='Contiene spoilers'),
        ),
    ]
